<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>EventManagement.Events.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.15" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.15" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventManagement.Events.Application\EventManagement.Events.Application.csproj" />
    <ProjectReference Include="..\EventManagement.Events.Domain\EventManagement.Events.Domain.csproj" />
    <ProjectReference Include="..\EventManagement.Logging\EventManagement.Logging.csproj" />
  </ItemGroup>

</Project>
