<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>EventManagement.Bookings.Presentation</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <UserSecretsId>event-management-bookings-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.15">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventManagement.Bookings.Application\EventManagement.Bookings.Application.csproj" />
    <ProjectReference Include="..\EventManagement.Bookings.Domain\EventManagement.Bookings.Domain.csproj" />
    <ProjectReference Include="..\EventManagement.Bookings.Infrastructure\EventManagement.Bookings.Infrastructure.csproj" />
    <ProjectReference Include="..\EventManagement.Logging\EventManagement.Logging.csproj" />
  </ItemGroup>

</Project>
