FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY EventManagement.sln ./
COPY src/ ./src/

RUN dotnet restore "src/EventManagement.Booking/EventManagement.Bookings.csproj"
RUN dotnet publish "src/EventManagement.Booking/EventManagement.Bookings.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "EventManagement.Bookings.dll"]
