@EventManagement_HostAddress = http://localhost:5167

GET {{EventManagement_HostAddress}}/api/v1/events
Accept: application/json

###

POST {{EventManagement_HostAddress}}/api/v1/events
Content-Type: application/json
Accept: application/json

{
  "title": "Demo event",
  "description": "Created from .http file",
  "startAt": "2026-03-03T10:00:00Z",
  "endAt": "2026-03-03T12:00:00Z"
}

###
